In [1]:
import os
import pandas as pd

In [2]:
local_file = "/mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/categories.txt"

In [7]:
df = pd.read_csv(local_file)
df.head()

   Category                      ScientificName
0         0  Miconia approximata Gamba & Almeda
1         1  Miconia ibaguensis (Bonpl.) Triana
2         2          Leandra nianga (DC.) Cogn.
3         3       Tibouchina semidecandra Cogn.
4         4        Miconia racemosa (Aubl.) DC.

In [9]:
df["folder_name"] = df["ScientificName"].str.split(" ").str[0] + "+" + df["ScientificName"].str.split(" ").str[1]
df.head()

   Category                      ScientificName              folder_name
0         0  Miconia approximata Gamba & Almeda      Miconia+approximata
1         1  Miconia ibaguensis (Bonpl.) Triana       Miconia+ibaguensis
2         2          Leandra nianga (DC.) Cogn.           Leandra+nianga
3         3       Tibouchina semidecandra Cogn.  Tibouchina+semidecandra
4         4        Miconia racemosa (Aubl.) DC.         Miconia+racemosa

In [27]:
base_dir = "/mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train"

In [28]:
import pathlib

for p in pathlib.Path(base_dir).glob("*"):
    src = os.path.join(p)
    mask = df["Category"] == int(p.name)
    label = df.loc[mask, "folder_name"].values[0]
    dst = os.path.join(p.parent, label)
    # os.makedirs(dst, exist_ok=True)
    os.system(f"mv \"{src}\" \"{dst}\"")

    print(f"src {src}")
    print(f"dst {dst}")

src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/382
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Miconia+rubiginosa
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/227
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Rhexia+alifanus
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/101
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Tibouchina+laxa
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/17
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Graffenrieda+harlingii
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/368
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Aciotis+rubricaulis
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/624
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Clidemia+setosa
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/252
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Adelobotrys+permixta
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/614
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Miconia+impetiolaris
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/91
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Meriania+tomentosa
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/341
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Miconia+radula
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/412
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Miconia+rufescens
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/136
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Miconia+brevipes
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/347
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Leandra+multiplinervis
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/106
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Clidemia+septuplinervia
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/292
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Blakea+parasitica
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/345
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Mouriri+acutiflora
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/284
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Clidemia+capitata
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/242
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Tibouchina+gardneriana
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/484
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Rhexia+nashii
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/524
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Miconia+multispicata
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/114
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Leandra+xanthocoma
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/575
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Ossaea+amygdaloides
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/95
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Miconia+decurrens
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/33
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Miconia+lateriflora
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/414
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Microlicia+graveolens
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/239
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Aciotis+annua
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/311
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Tibouchina+candolleana
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/234
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Miconia+chionophila
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/287
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Miconia+elata
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/438
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Cambessedesia+hilariana
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/417
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Mecranium+multiflorum
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/501
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Miconia+latifolia
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/339
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Tetrazygia+crotonifolia
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/500
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Miconia+ternatifolia
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/424
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Conostegia+volcanalis
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/588
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Miconia+foveolata
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/309
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Cambessedesia+corymbosa
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/322
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Miconia+ioneura
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/545
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Miconia+eriocalyx
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/621
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Blakea+bracteata
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/69
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Tibouchina+bicolor
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/374
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Graffenrieda+latifolia
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/362
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Miconia+aspergillaris
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/262
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Miconia+spinulosa
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/648
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Miconia+bractiflora
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/278
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Monochaetum+humboldtianum
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/603
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Miconia+dolichopoda
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/99
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Leandra+salicina
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/580
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Miconia+alborufescens
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/111
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Bellucia+arborescens
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/232
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Leandra+amplexicaulis
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/487
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Clidemia+umbrosa
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/404
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Miconia+chamissois
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/250
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Miconia+fasciculata
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/118
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Tetrazygia+discolor
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/525
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Miconia+multiflora
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/88
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Conostegia+speciosa
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/544
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Miconia+cubatanensis
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/197
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Bellucia+grossularioides
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/554
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Mouriri+nervosa
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/571
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Brachyotum+confertum
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/493
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Miconia+lonchophylla
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/314
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Brachyotum+jamesonii
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/73
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Clidemia+epiphytica
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/297
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Tibouchina+moritziana
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/35
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Tetrazygia+fadyenii
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/325
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Brachyotum+ledifolium
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/611
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Tibouchina+ochypetala
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/7
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Miconia+corymbiformis
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/43
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Tibouchina+heteromalla
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/201
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Miconia+solearis
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/187
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Miconia+tetrandra
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/523
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Clidemia+conglomerata
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/423
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Macairea+thyrsiflora
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/597
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Miconia+aureoides
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/474
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Tibouchina+granulosa
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/632
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Miconia+centrodesma
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/476
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Tetrazygia+urbani
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/84
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Tetrazygia+bicolor
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/277
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Graffenrieda+miconioides
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/90
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Tococa+bullifera
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/318
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Rhexia+lutea
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/119
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Mouriri+myrtilloides
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/671
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Blakea+foliacea
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/296
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Pterogastra+divaricata
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/41
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Leandra+carassana
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/218
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Leandra+glandulifera
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/576
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Leandra+lacunosa
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/306
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Henriettea+seemannii
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/13
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Clidemia+debilis
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/584
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Comolia+montana
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/60
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Pachyloma+huberioides
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/408
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Tibouchina+cubense
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/490
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Miconia+calycina
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/512
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Maieta+poeppigii
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/108
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Miconia+pyrifolia
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/547
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Purpurella+grossa
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/591
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Miconia+paniculata
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/34
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Miconia+holosericea
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/47
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Ossaea+pauciflora
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/137
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Miconia+loreyoides
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/619
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Graffenrieda+gracilis
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/29
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Marcetia+ericoides
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/616
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Clidemia+blepharodes
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/649
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Meriania+phlomoides
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/181
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Miconia+schlechtendalii
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/157
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Miconia+spennerostachya
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/672
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Miconia+dodecandra
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/378
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Miconia+ulmarioides
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/93
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Miconia+tristis
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/26
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Mouriri+francavillana
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/670
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Blakea+storkii
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/134
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Ossaea+microphylla
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/298
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Miconia+smaragdina
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/397
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Pilocosta+nana
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/122
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Leandra+melanodesma
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/194
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Leandra+australis
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/162
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Comolia+vernicosa
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/61
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Blakea+portentosa
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/680
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Tococa+subciliata
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/679
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Axinaea+sclerophylla
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/551
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Conostegia+xalapensis
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/330
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Miconia+alata
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/267
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Miconia+theizans
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/388
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Miconia+minutiflora
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/530
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Miconia+stenostachya
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/592
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Miconia+glaberrima
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/276
dst /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Rhexia+cubensis
src /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/206

# Removo espécies que tem mais de uma subespécie

In [32]:
import shutil

for l in os.listdir(base_dir):
    for l2 in os.listdir(os.path.join(base_dir, l)):
        if os.path.isdir(os.path.join(base_dir, l, l2)):
            print(f"removido {os.path.join(base_dir, l)}")
            shutil.rmtree(os.path.join(base_dir, l))

removido /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Clidemia+ciliata
removido /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Miconia+ceramicarpa
removido /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Miconia+impetiolaris
removido /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Miconia+argyrophylla
removido /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Clidemia+capitellata
removido /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Clidemia+octona
removido /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Mecranium+integrifolium
removido /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Miconia+theaezans
removido /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Rhexia+mariana
removido /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Mouriri+myrtilloides
removido /mnt/eec07521-c36a-4d2b-9047-0110e7749eae/TAN2019/small-train/Clidemia+hirta

In [33]:
for l in os.listdir(base_dir):
    for l2 in os.listdir(os.path.join(base_dir, l)):
        if os.path.isdir(os.path.join(base_dir, l, l2)):
            print(f"diretorio {os.path.join(base_dir, l)} tem pasta")

# Inicialmente, o dataset tinha 683 subespécies, após o processamento ele ficou com 659 espécies